#!/usr/bin/env ruby



  # ENV["RAILS_ENV"] = 'development'
  ENV["RAILS_ENV"] = RAILS_ENV = ARGV[0] || "development"

  #set up the rails environment
  require File.dirname(__FILE__) + "/../config/environment"   
  
  lockfile = "#{RAILS_ROOT}/public/fetch.lock"

begin  
  unless (File.exists?(lockfile) && File.mtime(lockfile) > 60.minutes.ago)
      File.open( lockfile, 'w' ) { |f| f.write(nil) }
      FileUtils.chmod 0777, lockfile 
      
      TwitterFetch.fetch
      NuvoFetch.fetch
      RtvFetch.fetch
      WibcFetch.fetch
      WishFetch.fetch
      WthrFetch.fetch
      FlickrFetch.fetch 
      Indystar.fetch
      IbjFetch.fetch
    
  end  
ensure
  File.delete(lockfile)
end
  

